spring:
  application:
    name: SpringBatch
  datasource:
    url: jdbc:mysql://localhost:3306/springbatch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Ravi@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mysql.sql
    job:
      enabled: false
server:
  port: 8888
  
